// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqgvbeceqrglolmjidpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZ3ZiZWNlcXJnbG9sbWppZHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjI0ODksImV4cCI6MjA2OTMzODQ4OX0.wulSmkwgKuz5HmFE8SLk-ZpC_K1SKBRr_7ul8aHNjaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});